apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: base10-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: base10-admin-service
spec:
  selector:
    app: base10-admin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer